image_path: testtube.png # the name of your sprite file
scale: 0.5 # Scale the size of your Sprite
start_pos: [1000,10] # the pixel coordinates of the start [0,0] is the top left pixel.
move: 20 # The number of pixels you want your sprite to move